update workflow

diff --git a/.github/workflows/vale.yml b/.github/workflows/vale.yml
--- a/.github/workflows/vale.yml
+++ b/.github/workflows/vale.yml
@@ -58,21 +58,36 @@ jobs:
             fi
           done
 
-      - name: Run vale
+      - name: Check for Vale issues
+        id: check-vale
+        if: ${{ steps.changed-files.outputs.any_changed == 'true' }}
+        shell: bash
+        run: |
+          set +e
+          vale ${{ steps.changed-files.outputs.all_changed_and_modified_files }}
+          exit_code=$?
+          echo "Exit code: $exit_code"
+          if [ $exit_code -ne 0 ]; then
+            echo "issues_found=true" >> $GITHUB_OUTPUT
+          else
+            echo "issues_found=false" >> $GITHUB_OUTPUT
+          fi
+
+      - name: Run Vale (Annotations)
         if: ${{ steps.changed-files.outputs.any_changed == 'true' }}
         uses: errata-ai/vale-action@reviewdog
         with:
           token: ${{ secrets.GITHUB_TOKEN }}
-          reporter: github-check
+          reporter: github-check  # Use 'github-check' to post annotations without failing the check
           files: ${{ steps.changed-files.outputs.all_changed_and_modified_files }}
           separator: ' '
           version: '2.27.0'
+          fail_on_error: false  # Ensure the step doesn't fail even if issues are found
 
       - name: Post summary comment
-        if: ${{ steps.changed-files.outputs.any_changed == 'true' }}
+        if: ${{ steps.check-vale.outputs.issues_found == 'true' }}
         run: |
-          COMMENT="❗️Oh no, some Vale linting found issues! Please check the **Files change** tab for detailed results and make the necessary updates."
-          COMMENT+=$'\n'
+          COMMENT="❗️Oh no, Vale linting found some issues! Please check the **Files changed** tab for detailed results and make the necessary updates."
           COMMENT+=$'\n\n'
           COMMENT+="➡️ Link to detailed report: [Files changed](${{ github.event.pull_request.html_url }}/files)"
           gh pr comment ${{ github.event.pull_request.number }} --body "$COMMENT"
